function k(b,a,c,d,e){b.h.Aa(b.T,a,c,d,e)}function m(b,a,c,d){b.h.s?k(b,a,c,d):b.h.Hb()._OnMessageFromDOM({type:"event",component:b.T,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.h.i(b.T,a,c)}function p(b,a){for(const [c,d]of a)n(b,c,d)}window.ca=class{constructor(b,a){this.h=b;this.T=a;this.ha=!1;this.ob=()=>this.Xa()}Ua(){}Xa(){}};
window.yb=class{constructor(b){this.gb=b;this.Ub=5;this.M=-1;this.ja=-Infinity;this.Zb=()=>{this.M=-1;this.ja=Date.now();this.U=!0;this.gb();this.U=!1};this.hb=this.U=!1}};"use strict";function aa(b,a){const c=a.elementId,d=b.va(c,a);b.l.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{q(b,"elem-focused",c)});d.addEventListener("blur",()=>{q(b,"elem-blurred",c)});b.R&&document.body.appendChild(d)}
function r(b,a,c){n(b,a,d=>{const e=b.l.get(d.elementId);return c(e,d)})}function q(b,a,c,d){d||={};d.elementId=c;k(b,a,d)}
window.Wa=class extends self.ca{constructor(b,a){super(b,a);this.l=new Map;this.R=!0;p(this,[["create",c=>aa(this,c)],["destroy",c=>{c=c.elementId;const d=this.l.get(c);this.xa(d);this.R&&d.parentElement.removeChild(d);this.l.delete(c)}],["set-visible",c=>{this.R&&(this.l.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.R){var d=this.l.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=c.height+"px";c=c.fontSize;
null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.l.get(c.elementId);this.Ba()}],["focus",c=>this.Fa(c)],["set-css-style",c=>{this.l.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.l.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.l.get(c.elementId).removeAttribute(c.name)}]]);r(this,"get-element",c=>c)}va(){throw Error("required override");}xa(){}Ba(){throw Error("required override");}Fa(b){var a=this.l.get(b.elementId);b.focus?a.focus():
a.blur()}};"use strict";const t=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let w=0;function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.dc?new Promise(c=>{const d="c3_resolve_"+w;++w;self[d]=c;a.textContent=b.ic+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let y=!1,z=!1;
function ba(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let B=new Audio;const da={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;
async function ea(b){b=await fa(b);return(new TextDecoder("utf-8")).decode(b)}function fa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ha=0;const ia=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ia.push(b)};const ja=new Set(["cordova","playable-ad","instant-games"]);
let ka=!1;
window.A=class b{constructor(a){this.s=a.kc;this.W=null;this.o="";this.ra=a.hc;this.ba={};this.Pa=this.pb=null;this.ga=[];this.j=this.$=null;this.kb=!1;this.V=null;this.K=-1;this.Xb=()=>this.Ob();this.J=[];this.g=a.qb;this.Na="file"===location.protocol.substr(0,4);!this.s||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ba()||(this.s=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.s=!1;if("cordova"===this.g&&this.s)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.s=!1)}else this.s=!1;this.la=this.v=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("runtime","cordova-fetch-local-file",c=>this.Kb(c));this.i("runtime","create-job-worker",()=>this.Lb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.ab(a)):this.ab(a)}vb(){return t&&
"cordova"===this.g}za(){const a=navigator.userAgent;return t&&ja.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}tb(){return u}ya(){return u&&ja.has(this.g)}async ab(a){"macos-wkwebview"===this.g&&this.Ia({type:"ready"});if("playable-ad"===this.g){this.v=self.c3_base64files;this.la={};await this.Db();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d].toLowerCase();this.la.hasOwnProperty(c)?a.N[d]={dc:!0,ic:this.la[c]}:this.v.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.v[c]))}}a.fc?
this.o=a.fc:(c=location.origin,this.o=("null"===c?"file:///":c)+location.pathname,c=this.o.lastIndexOf("/"),-1!==c&&(this.o=this.o.substr(0,c+1)));a.mc&&(this.ba=a.mc);c=new MessageChannel;this.W=c.port1;this.W.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Nb(d));this.V=new self.wb(this);await la(this.V);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.s?await this.Jb(a,c.port2):await this.Ib(a,c.port2)}Da(a){a=this.ba.hasOwnProperty(a)?this.ba[a]:a.endsWith("/workermain.js")&&this.ba.hasOwnProperty("workermain.js")?this.ba["workermain.js"]:"playable-ad"===this.g&&this.v.hasOwnProperty(a.toLowerCase())?this.v[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async wa(a,c,d){if(a.startsWith("blob:"))return new Worker(a,
d);if("cordova"===this.g&&this.Na)return a=await this.ua(d.cc?a:this.ra+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}B(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}$a(a){var c=this.o,d=location.href,e=this.B(),f=this.u(),g=window.devicePixelRatio,
h=b.P(),l=a.sc,v=window.cr_previewImageBlobs||this.v,wa=window.cr_previewProjectFileBlobs,xa=window.cr_previewProjectFiles,ya=window.qc||"";a=a.qb;var za=(new URLSearchParams(self.location.search)).has("debug"),K=this.V;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:v,previewProjectFileBlobs:wa,previewProjectFileSWUrls:xa,swClientId:ya,exportType:a,isDebug:za,ife:!!self.rc,jobScheduler:{inputPort:K.Ma,outputPort:K.Qa,
maxNumWorkers:K.Wb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ra+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ra+"opus.wasm.wasm",isFileProtocol:this.Na,isiOSCordova:this.vb(),isiOSWebView:this.za(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Jb(a,c){var d=this.Da(a.lc);this.pb=await this.wa(d,this.o,{type:"module",name:"Runtime",cc:!0});this.j=document.createElement("canvas");this.j.style.display="none";d=this.j.transferControlToOffscreen();
document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Ta||[],f=a.N;e=await Promise.all(e.map(g=>this.G(g)));f=await Promise.all(f.map(g=>this.G(g)));if("cordova"===this.g)for(let g=0,h=a.ta.length;g<h;++g){const l=a.ta[g],v=l[0];if(v===a.Sa||"scriptsInEvents.js"===v||v.endsWith("/scriptsInEvents.js"))l[1]=await this.G(v)}this.pb.postMessage(Object.assign(this.$a(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,
workerDependencyScripts:e,engineScripts:f,projectScripts:a.ta,mainProjectScript:a.Sa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ma(this.V)]);this.ga=E.map(g=>new g(this));this.Za();self.c3_callFunction=(g,h)=>{var l=this.$;return l.h.xb(l.T,{name:g,params:h})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.Aa("runtime","go-to-last-error-script"))}async Ib(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ga=E.map(g=>new g(this));this.Za();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.o)).toString():g);Array.isArray(a.Ta)&&d.unshift(...a.Ta);d=await Promise.all(d.map(g=>this.G(g)));await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;const e=a.Sa,f=a.ta;for(let [g,h]of f)if(h||=g,g===e)try{h=await this.G(h),await x(h),"preview"!==this.g||d[g]||this.cb(g,"main script did not run to completion")}catch(l){this.cb(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.G(h),await x(h);"preview"===this.g&&"object"!==typeof self.nc.oc?(this.ea(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.$a(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ia}),this.bb(),this.Pa=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Pa,a))}cb(a,c){this.ea();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}bb(){this.ea()}ea(){const a=window.ac;a&&(a.parentElement.removeChild(a),window.ac=null)}async Lb(){const a=await na(this.V);return{outputPort:a,transferables:[a]}}Hb(){if(this.s)throw Error("not available in worker mode");
return this.Pa}Aa(a,c,d,e,f){this.W.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}xb(a,c){const d=ha++,e=new Promise((f,g)=>{G.set(d,{resolve:f,reject:g})});this.W.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Mb(a);if("result"===c)this.Pb(a);else if("runtime-ready"===c)this.Qb();else if("alert-error"===c)this.ea(),
alert(a.message);else if("creating-runtime"===c)this.bb();else throw Error(`unknown message '${c}'`);}Mb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.da(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.da(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.da(f,!1,""+h)}):this.da(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}da(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.W.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Pb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}i(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static O(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Za(){for(const a of this.ga)if("runtime"===
a.T){this.$=a;return}throw Error("cannot find runtime DOM handler");}Nb(a){this.Aa("debugger","message",a)}Qb(){for(const a of this.ga)a.Ua()}static P(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static fa(a){ka=!!a}Ab(a){this.J.push(a);this.Ha()}Sb(a){a=this.J.indexOf(a);if(-1===a)throw Error("invalid callback");this.J.splice(a,1);this.J.length||this.Ya()}Ha(){-1===this.K&&this.J.length&&(this.K=requestAnimationFrame(this.Xb))}Ya(){-1!==
this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Ob(){this.K=-1;for(const a of this.J)a();this.Ha()}F(a){this.$.F(a)}D(a){this.$.D(a)}Ga(){this.$.Ga()}zb(){this.kb=!0}sb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ub(a){return!this.sb(a)}async G(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Na&&this.ub(a))?(a.startsWith(this.o)&&(a=a.substr(this.o.length)),a=await this.ua(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):
a}async Kb(a){const c=a.filename;switch(a.as){case "text":return await this.rb(c);case "buffer":return await this.ua(c);default:throw Error("unsupported type");}}Va(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async rb(a){a=await this.Va(a);return await ea(a)}Ca(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Eb(a.filename,a.jc,a.bc)}}ua(a){return new Promise((c,d)=>{C.push({filename:a,
jc:e=>{D--;this.Ca();c(e)},bc:e=>{D--;this.Ca();d(e)}});this.Ca()})}async Eb(a,c,d){try{const e=await this.Va(a),f=await fa(e);c(f)}catch(e){d(e)}}Ia(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Db(){const a=[];for(const [c,d]of Object.entries(this.v))a.push(this.Cb(c,d));await Promise.all(a)}async Cb(a,
c){if("object"===typeof c)this.v[a]=new Blob([c.str],{type:c.type}),this.la[a]=c.str;else{let d=await this.Gb(c);d||=this.Fb(c);this.v[a]=d}}async Gb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Fb(a){a=this.Rb(a);return this.Bb(a.data,a.ec)}Rb(a){var c=a.indexOf(",");if(0>
c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{ec:a,data:d}}Bb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const H=self.A;
function oa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},qa={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function ra(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function sa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await sa(b)}finally{URL.revokeObjectURL(b)}}
function ta(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function ua(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await ta(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function M(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const va=new Set(["input","textarea","datalist","select"]),Aa=new Set(["canvas","body","html"]);function N(b){Aa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ba(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await ua(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let O=!1;document.addEventListener("pause",()=>O=!0);document.addEventListener("resume",()=>O=!1);async function Ca(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Da(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ea(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Fa(b){self.setTimeout(()=>{b.ib=!0},1E3);"cordova"===b.h.g?(document.addEventListener("pause",()=>P(b,!0)),document.addEventListener("resume",()=>P(b,!1))):document.addEventListener("visibilitychange",()=>P(b,document.hidden));return{isSuspended:!(!document.hidden&&!O)}}
function Ga(b){b.fb||(b.fb=!0,window.addEventListener("deviceorientation",a=>{b.m||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.m||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ha(b){b.eb||(b.eb=!0,window.addEventListener("devicemotion",a=>{if(!b.m){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ia(b){await ra(b.url)}
function Ja(b,a){b.jb=a.message;-1===b.La&&(b.La=setTimeout(()=>{b.La=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.jb)},250))}function Q(b){if(!b.m){var a=H.P();a&&"any"!==b.Ra&&Ka(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.B(),innerHeight:b.u()})}}function R(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.P(),innerWidth:b.B(),innerHeight:b.u()})}
function P(b,a){a?b.h.Ya():b.h.Ha();k(b,"visibilitychange",{hidden:a})}function La(b,a,c){"Backspace"===c.key&&N(c);if(!b.m){var d=pa.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function S(b,a,c,d){b.m||oa(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function T(b){window!==window.top&&window.focus();Ma(b.target)&&document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur()}
function U(b,a,c){if(!b.m){if(b.Y&&"pointermove"!==a){var d=b.Y;d.U||(-1!==d.M&&(self.clearTimeout(d.M),d.M=-1),d.ja=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.X);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+b.oa,movementY:(c.movementY||0)+b.pa,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||
0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.oa=0;b.pa=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),S(b,d,c,qa),b.X=c.buttons)}}
function V(b,a,c){if(!b.m&&!oa(c)){var d=b.X;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.X=c.buttons;S(b,c.type,c,qa)}}
function W(b,a,c){if(!b.m)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},I)}}
function X(b,a){document.body.style.transform="";if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}function Na(b,a,c,d){const e=b.B(),f=b.u();b.L=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.P()}):10>d&&Oa(b,e,f,d+1)}
function Oa(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Na(b,a,c,d),48)}
function Ka(b){b=b.Ra;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ma(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.O(class extends self.ca{constructor(b){super(b,"runtime");this.lb=!0;this.L=-1;this.Ra="any";this.eb=this.fb=!1;this.C=null;this.m=!1;this.jb="";this.La=-1;this.H=this.Y=null;this.pa=this.oa=0;this.ib=!1;this.nb=b.B();this.ka=b.u();this.aa=0;b.i("canvas","update-size",d=>{var e=this.h;e.kb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.lb&&(e.style.display="",this.lb=!1))});b.i("runtime","invoke-download",
d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.i("runtime","raster-svg-image",d=>Ca(d));b.i("runtime","get-svg-image-size",d=>Da(d));b.i("runtime","set-target-orientation",d=>{this.Ra=d.targetOrientation});b.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.i("runtime","post-to-debugger",d=>Ea(d));b.i("runtime","go-to-script",d=>Ea(d));b.i("runtime",
"before-start-ticking",()=>Fa(this));b.i("runtime","debug-highlight",d=>{if(d.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.C&&(this.C.style.display="none")});b.i("runtime","enable-device-orientation",()=>Ga(this));b.i("runtime","enable-device-motion",()=>Ha(this));
b.i("runtime","add-stylesheet",d=>Ia(d));b.i("runtime","alert",d=>this.Ea(d));b.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.i("runtime","set-exporting-to-video",d=>{this.m=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.h.j.style.display="";this.h.zb()});b.i("runtime","export-to-video-progress",d=>
Ja(this,d));b.i("runtime","exported-to-video",d=>{window.$b({type:"exported-video",blob:d.blob,time:d.time})});b.i("runtime","exported-to-image-sequence",d=>{window.$b({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||M(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);c.addEventListener("selectstart",
N);c.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),c.addEventListener("pointerdown",N)):c.addEventListener("touchstart",N);this.X=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ba,{passive:!1});window.addEventListener("wheel",Ba,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.m){var d=this.B();
var e=this.u();if(this.h.ya()){if(this.ib){if(this.nb===d&&e<this.ka){this.aa=this.ka-e;X(this.ka,this.aa);d=void 0;break a}0<this.aa&&(this.aa=0,X(e,this.aa))}this.nb=d;this.ka=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.P()});this.h.za()&&(-1!==this.L&&clearTimeout(this.L),Na(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>Q(this));window.addEventListener("webkitfullscreenchange",()=>Q(this));window.addEventListener("mozfullscreenchange",
()=>Q(this));window.addEventListener("fullscreenerror",d=>R(this,d));window.addEventListener("webkitfullscreenerror",d=>R(this,d));window.addEventListener("mozfullscreenerror",d=>R(this,d));if(b.za())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=
new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):M(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.fa(!0),Q(this)):"exited-fullscreen"===d?(H.fa(!1),Q(this)):console.warn("Unknown wrapper message: ",d)};this.I=new Set;this.ma=new WeakSet;this.Vb=!1}Ua(){window.addEventListener("focus",()=>{k(this,"window-focus",null,J)});window.addEventListener("blur",
()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},J);this.X=0});window.addEventListener("focusin",a=>{a=a.target;(va.has(a.tagName.toLowerCase())||M(a))&&k(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.m||k(this,"wheel",{clientX:a.clientX,
clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{T(a);U(this,"pointerdown",a)}),this.h.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Y=new self.yb(()=>{U(this,"pointermove",this.H);this.H=null}),this.Y.hb=!0,window.addEventListener("pointerrawupdate",a=>{this.H&&(this.oa+=this.H.movementX||0,this.pa+=
this.H.movementY||0);this.H=a;a=this.Y;if(-1===a.M){var c=Date.now(),d=c-a.ja,e=a.Ub;d>=e&&a.hb?(a.ja=c,a.U=!0,a.gb(),a.U=!1):a.M=self.setTimeout(a.Zb,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>U(this,"pointermove",a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",
a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=()=>this.Ga();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.h.tb()&&!this.h.ya()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this.u(),navigator.virtualKeyboard.boundingRect.height)}))}B(){return this.h.B()}u(){return this.h.u()}Ga(){var b=[...this.I];this.I.clear();if(!this.Vb)for(const a of b)(b=a.play())&&b.catch(()=>{this.ma.has(a)||this.I.add(a)})}F(b){if("function"!==typeof b.play)throw Error("missing play function");
this.ma.delete(b);let a;try{a=b.play()}catch(c){this.I.add(b);return}a&&a.catch(()=>{this.ma.has(b)||this.I.add(b)})}D(b){this.I.delete(b);this.ma.add(b)}Ea(b){alert(b.message)}});"use strict";async function la(b){if(b.Tb)throw Error("already initialised");b.Tb=!0;var a=b.qa.Da("dispatchworker.js");b.Ka=await b.qa.wa(a,b.S,{name:"DispatchWorker"});a=new MessageChannel;b.Ma=a.port1;b.Ka.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Qa=await na(b)}function ma(b){return[b.Ma,b.Qa]}
async function na(b){const a=b.mb.length;var c=b.qa.Da("jobworker.js");c=await b.qa.wa(c,b.S,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Ka.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.mb.push(c);return e.port1}
self.wb=class{constructor(b){this.qa=b;this.S=b.o;this.S="preview"===b.g?this.S+"workers/":this.S+b.ra;this.Wb=Math.min(navigator.hardwareConcurrency||2,16);this.Ka=null;this.mb=[];this.Qa=this.Ma=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.A({kc:!0,lc:"workermain.js",N:["scripts/c3runtime.js"],ta:[],Sa:"",hc:"scripts/",Ta:[],qb:"html5"}));"use strict";
async function Pa(b,a){b.Oa=a.isInWorker;a=document.createElement("video");b.sa=!!a.requestVideoFrameCallback&&!b.h.ya();const c=!!self.createImageBitmap;b.Z=b.Oa||c;return{postImageBitmaps:b.Z,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Qa(b,a){if(!b.Ja.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Qa(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Y(b,a,c,d){b.Ja.has(a)||q(b,"playback-event",c,{type:d})}
self.A.O(class extends self.Wa{constructor(b){super(b,"video");this.Z=this.sa=this.Oa=this.R=!1;this.na=this.Yb=0;this.Ja=new WeakSet;n(this,"init",a=>Pa(this,a));r(this,"play",a=>{this.F(a)});r(this,"pause",a=>{this.D(a);a.pause()});r(this,"set-source",(a,c)=>{a.src=c.src;a.load()});r(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});r(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});r(this,"set-looping",(a,c)=>{a.loop=c.isLooping});r(this,"set-muted",(a,c)=>{a.muted=c.isMuted});r(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>this.l.get(a)}F(b){this.h.F(b);this.Z&&this.sa&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Qa(this,b)))}D(b){this.h.D(b);this.Z&&this.sa&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}va(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=!0;
c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Y(this,c,b,0));c.addEventListener("canplaythrough",()=>Y(this,c,b,1));c.addEventListener("ended",()=>Y(this,c,b,2));c.addEventListener("error",()=>Y(this,c,b,3));c.addEventListener("loadstart",()=>Y(this,c,b,4));c.addEventListener("playing",()=>Y(this,c,b,5));c.addEventListener("pause",()=>Y(this,c,b,6));c.addEventListener("stalled",()=>Y(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.F(c);this.na++;this.ha||(this.h.Ab(this.ob),this.ha=!0);return c}Ba(){}xa(b){this.D(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.na=Math.max(this.na-1,0);0===this.na&&this.ha&&(this.h.Sb(this.ob),this.ha=!1);this.Ja.add(b)}Xa(){const b={},a={sequenceNumber:this.Yb++,videoData:b},c=[],d=[];for(const [e,f]of this.l.entries()){const g={currentTime:f.currentTime,playbackRate:f.playbackRate,
duration:f.duration,videoWidth:f.videoWidth,videoHeight:f.videoHeight};if(this.Z)if(this.sa){const h=f.c3_imageBitmap;f.c3_imageBitmap=null;(g.imageBitmap=h)&&c.push(h)}else d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>{this.Oa?k(this,"state",a,!1,c):m(this,"state",a)})}});"use strict";
function Ra(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Sa(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.A.O(class extends self.ca{constructor(b){super(b,"browser");this.g="";p(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Ra(this)],["alert",a=>this.Ea(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Fa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Sa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.pc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.A.fa(!0),this.h.Ia({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(c):a.mozRequestFullScreen?a.mozRequestFullScreen(c):a.msRequestFullscreen?a.msRequestFullscreen(c):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.g||"macos-wkwebview"===this.g?(self.A.fa(!1),this.h.Ia({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Ea(b){alert(b.message)}Fa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";async function Ta(b,a){a=a.type;let c=!0;0===a?c=await Ua():1===a&&(c=await Va());k(b,"permission-result",{type:a,result:c})}
async function Ua(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Va(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.A.O(class extends self.ca{constructor(b){super(b,"touch");n(this,"request-permission",a=>Ta(this,a))}});"use strict";function Xa(b,a,c){Z(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.ia=!0}
function Z(b,a,c){a.src&&a.src.startsWith("blob:")&&b.ia&&URL.revokeObjectURL(a.src);a.src=c}
self.A.O(class extends self.Wa{constructor(b){super(b,"iframe");this.ia=!1;r(this,"navigate-url",(a,c)=>{Z(this,a,c.url);this.ia=!1});r(this,"display-html",(a,c)=>Xa(this,a,c))}va(b,a){b=document.createElement("iframe");b.style.position="absolute";b.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(b.setAttribute("noresize","noresize"),b.setAttribute("scrolling","no"));a.isVisible||
(b.style.display="none");a.id&&(b.id=a.id);a.allow&&(b.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&b.setAttribute("allowfullscreen",""));a.enableSandbox&&b.setAttribute("sandbox",a.sandbox);a.url?b.src=a.url:a.html&&Xa(this,b,a);return b}Ba(){}xa(b){Z(this,b,"");this.ia=!1}});
